#!/bin/bash
alias reload_zshrc="source ~/.zshrc"
alias reload_aliases="source ~/.aliases"
alias aliases="vim ~/.aliases && reload_aliases"
alias show_aliases="less ~/.aliases"
alias zshrc='vim ~/.zshrc && reload_zshrc'

unalias ls
alias ls='ls --color=auto'

alias rs='rails server'
alias rg='rails generate'
alias rag='rake generate'
alias gs="git status"
alias gca="git commit --amend"
alias lg='git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"'


alias fact="elinks -dump randomfunfacts.com | sed -n '/^| /p' | tr -d \|"

alias emacs='emacs -nw'
alias gvim='gvim -p --remote-tab-silent'

alias ls='ls -h'
alias ff_profiles='/Applications/Firefox.app/Contents/MacOS/firefox-bin -p'
alias kbrd="setxkbmap -model pc104 -layout us,bg -variant ,phonetic && setxkbmap -option grp:alt_caps_toggle"
alias lock="xscreensaver-command --lock"

#alias ssh='ssh-ident'
tssh (){ ssh -t "$1" 'tmux attach -t ``|| tmux new || screen -DR'; }
