#!/bin/bash

#######################
# dotfile management #
#######################

alias aliases="vim ~/.aliases && reload_aliases"
alias reload_zshrc="source ~/.zshrc"
alias reload_aliases="source ~/.aliases"
alias show_aliases="less ~/.aliases"
alias zshrc='vim ~/.zshrc && reload_zshrc'


###########
# various #
###########
if [[ $platform == 'macosx' ]]; then
	alias ls='ls -h'
    alias ff_profiles='/Applications/Firefox.app/Contents/MacOS/firefox-bin -p'
    alias o="open ."
    alias gvim="mvim --remote-silent"
fi

if [[ $platform == 'linux' ]]; then
	alias ls='ls --color=auto'
	alias gvim='gvim -p --remote-tab-silent'
fi


#########
# emacs #
#########
alias vim='emacsclient -t'
alias gvim='emacsclient -c'
alias emacsd='/usr/bin/emacs --daemon=server'
alias emacsc='emacsclient -c'
alias emacs='emacsclient -t'

##########
# scheme #
##########
alias racket='racket -il readline'

###############
# common lisp #
###############
alias sbcl='rlwrap sbcl'

alias kbrd="setxkbmap -model pc104 -layout us,bg -variant ,phonetic && setxkbmap -option grp:alt_caps_toggle"
alias lock="xscreensaver-command --lock"

#alias ssh='ssh-ident'
tssh (){ ssh -t "$1" 'tmux attach -t ``|| tmux new || screen -DR'; }
