require 'rake'
require 'fileutils'
include FileUtils

namespace :vim do
  namespace :bundles do
    desc "Upgrate all bundles to their latest commits"
    task :update do
      each_bundle do |path|
        puts "Updating #{path}..."

        system 'git fetch'
        system 'git checkout --quiet --detach master'
      end
    end

    desc "Clean up tags generated by vim bundles"
    task :clean do
      each_bundle do |path|
        puts "Cleaning #{path}..."

        system 'git clean --force'
      end
    end
  end

  namespace :install do
    desc "Installs Vundle.vim"
    task :vundle do
      unless File.exists? 'vim/bundle/Vundle.vim'
        system 'git clone https://github.com/gmarik/Vundle.vim.git vim/bundle/Vundle.vim'
      end
    end
  end
end

namespace :ruby do
  desc "Install rbenv"
  task :rbenv do
    unless File.exists? 'rbenv'
      system 'git clone https://github.com/sstephenson/rbenv.git rbenv'
      system 'rehash'
    end
  end
  desc "Install ruby_build"
  task :ruby_build do
    unless File.exists? 'rbenv/plugins/ruby-build'
      system 'git clone https://github.com/sstephenson/ruby-build.git rbenv/plugins/ruby-build'
    end
  end
  desc "Install ruby 2.2.0"
  task :ruby do
    system 'rbenv install 2.2.0'
    system 'rbenv rehash'
    system 'rbenv global 2.2.0'
  end
end

desc "Install into the users home"
task :install do
  Dir['*'].each do |file|
    case file
      when 'Rakefile', 'README.md'
        next
      when 'Xresources', 'Xmodmap', 'xprofile'
        link_file file, home_slash(".#{file}") if `uname -s`.include? 'Linux'
      when 'bin'
        unless File.directory? home_slash('.bin')
          mkdir home_slash('.bin'), :verbose => false
        end

        Dir['bin/*'].each do |bin_file|
          link_file bin_file, home_slash(".#{bin_file}")
        end
      when 'quicksynergy'
        unless File.directory? home_slash('.quicksynergy')
            mkdir home_slash('.quicksynergy'), :verbose => false if `uname -s`.include? 'Linux'
        end

        Dir['quicksynergy/*'].each do |conf_file|
          link_file conf_file, home_slash(".#{conf_file}") if `uname -s`.include? 'Linux'
        end

      when 'moc'
        unless File.directory? home_slash('.moc')
            mkdir home_slash('.moc'), :verbose => false if `uname -s`.include? 'Linux'
        end

        Dir['moc/*'].each do |conf_file|
          link_file conf_file, home_slash(".#{conf_file}") if `uname -s`.include? 'Linux'
        end
      else
        link_file file, home_slash(".#{file}")
    end
  end
end

def home() ENV['HOME'] end

def home_slash(name) File.join(home, name) end

def link_file(source, target)
  action = if File.exist?(target)
    if $replace_all
      :overwrite
    else
      print "Overwrite #{target}? [yNqa] "
      case $stdin.gets.chomp
        when 'a' then ($replace_all = true) and :overwrite
        when 'y' then :overwrite
        when 'q' then exit
        else :skip
      end
    end
  else
    :link
  end

  if [:link, :overwrite].include? action
    if action == :overwrite
      puts "Overwriting #{target}"
      rm target, :verbose => false
    end
    ln_s File.join(Dir.pwd, source), target, :verbose => true
  elsif action == :skip
    puts "skipping #{target}"
  end
end
